# -*- coding: utf-8 -*-
"""Db-net.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ELZUNcWd5fFtNApz1MtBRgCvDyotR2xw
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install gdown

# Download directly to Colab (faster, avoids Drive timeout)
!gdown --fuzzy "https://drive.google.com/file/d/1DA5cQdKfpwouDy8UtXhIEjvMSv_mU8LR/view" -O /content/PoVSSeg.zip

# Unzip inside Colab's local storage
!unzip -q "/content/PoVSSeg.zip" -d /content/PoVSSeg/

!ls /content/PoVSSeg/

!ls /content/PoVSSeg/Somke_day
!ls /content/PoVSSeg/Somke_day/image | head
!ls /content/PoVSSeg/Somke_day/label | head
!head /content/PoVSSeg/Somke_day/Smoke_splits/train.txt

import os

train_txt = '/content/PoVSSeg/Somke_day/Smoke_splits/train.txt'
val_txt = '/content/PoVSSeg/Somke_day/Smoke_splits/val.txt'

with open(train_txt) as f:
    train_ids = [line.strip() for line in f if line.strip()]

with open(val_txt) as f:
    val_ids = [line.strip() for line in f if line.strip()]

print("Train samples:", len(train_ids))
print("Val samples:", len(val_ids))
print("Example IDs:", train_ids[:5])

import cv2
import numpy as np
from tqdm import tqdm

TARGET_W, TARGET_H = 960, 540
GRID_W, GRID_H = 60, 34
THRESHOLD = 0.10

image_dir = '/content/PoVSSeg/Somke_day/image'
label_dir = '/content/PoVSSeg/Somke_day/label'

out_img_train = '/content/processed/train/images'
out_lbl_train = '/content/processed/train/labels'
out_img_val = '/content/processed/val/images'
out_lbl_val = '/content/processed/val/labels'

for d in [out_img_train, out_lbl_train, out_img_val, out_lbl_val]:
    os.makedirs(d, exist_ok=True)

def resize_and_blockify(img_path, mask_path, out_img_path, out_lbl_path):
    # Read files
    img = cv2.imread(img_path, cv2.IMREAD_COLOR)
    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
    if img is None or mask is None:
        print("Missing file:", img_path, mask_path)
        return

    # Resize image and mask
    img = cv2.resize(img, (TARGET_W, TARGET_H), interpolation=cv2.INTER_LINEAR)
    mask = cv2.resize(mask, (TARGET_W, TARGET_H), interpolation=cv2.INTER_NEAREST)

    # Convert to block labels
    block_h, block_w = TARGET_H // GRID_H, TARGET_W // GRID_W
    block_labels = np.zeros((GRID_H, GRID_W), dtype=np.uint8)
    for gy in range(GRID_H):
        for gx in range(GRID_W):
            x0, x1 = gx * block_w, (gx + 1) * block_w
            y0, y1 = gy * block_h, (gy + 1) * block_h
            block = mask[y0:y1, x0:x1]
            smoke_fraction = np.count_nonzero(block) / (block_w * block_h)
            block_labels[gy, gx] = 1 if smoke_fraction >= THRESHOLD else 0

    # Save resized image and block label
    cv2.imwrite(out_img_path, img)
    np.save(out_lbl_path, block_labels)

def normalize_id(raw_id):
    return raw_id.replace("label", "").strip()

with open(train_txt) as f:
    train_ids = [normalize_id(line) for line in f if line.strip()]

with open(val_txt) as f:
    val_ids = [normalize_id(line) for line in f if line.strip()]

for id in tqdm(train_ids, desc="Processing train set"):
    img_path = os.path.join(image_dir, f"img{id}.png")
    mask_path = os.path.join(label_dir, f"label{id}.png")
    out_img_path = os.path.join(out_img_train, f"{id}.jpg")
    out_lbl_path = os.path.join(out_lbl_train, f"{id}.npy")
    resize_and_blockify(img_path, mask_path, out_img_path, out_lbl_path)

# --- 6. Process validation set ---
for id in tqdm(val_ids, desc="Processing val set"):
    img_path = os.path.join(image_dir, f"img{id}.png")
    mask_path = os.path.join(label_dir, f"label{id}.png")
    out_img_path = os.path.join(out_img_val, f"{id}.jpg")
    out_lbl_path = os.path.join(out_lbl_val, f"{id}.npy")
    resize_and_blockify(img_path, mask_path, out_img_path, out_lbl_path)

import cv2

import matplotlib.pyplot as plt
import random

sample_id = random.choice(train_ids)
img = cv2.imread(f"{out_img_train}/{sample_id}.jpg")
lbl = np.load(f"{out_lbl_train}/{sample_id}.npy")

plt.figure(figsize=(8,4))
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.imshow(cv2.resize(lbl*255, (img.shape[1], img.shape[0])), alpha=0.4, cmap='Reds')
plt.title(f"Overlay for ID {sample_id}")
plt.axis('off')
plt.show()

import os
import cv2
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

# --- Normalization for RGB images (ImageNet stats are a good default) ---
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])

class SmokeDataset(Dataset):
    def __init__(self, img_dir, lbl_dir, augment=False):
        self.img_files = sorted(os.listdir(img_dir))
        self.lbl_files = sorted(os.listdir(lbl_dir))
        self.img_dir = img_dir
        self.lbl_dir = lbl_dir
        self.augment = augment

        self.to_tensor_norm = transforms.Compose([
            transforms.ToTensor(),  # H,W,C → C,H,W and 0..1 scaling
            normalize
        ])
        self.color = transforms.ColorJitter(0.1, 0.1, 0.1, 0.05) if augment else None

    def __len__(self):
        return len(self.img_files)

    def __getitem__(self, idx):
        # --- Load image ---
        img_path = os.path.join(self.img_dir, self.img_files[idx])
        img_bgr = cv2.imread(img_path, cv2.IMREAD_COLOR)
        img = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)  # shape H×W×3

        # --- Load label ---
        lbl_path = os.path.join(self.lbl_dir, self.lbl_files[idx])
        target = np.load(lbl_path).astype(np.int64)  # shape 34×60, values 0/1

        # --- Convert to tensor ---
        img = self.to_tensor_norm(img)               # shape 3×540×960
        target = torch.from_numpy(target)            # shape 34×60

        # --- Augmentation ---
        if self.augment:
            # Color jitter (image only)
            img = self.color(img)

            # Horizontal flip (image + label together)
            if torch.rand(1).item() < 0.5:
                img = torch.flip(img, dims=[2])       # flip width of image [C,H,W]
                target = torch.flip(target, dims=[1]) # flip width of grid [H_grid,W_grid]

        return img, target

# --- Build datasets ---
train_dataset = SmokeDataset('/content/processed/train/images',
                             '/content/processed/train/labels',
                             augment=True)

val_dataset = SmokeDataset('/content/processed/val/images',
                           '/content/processed/val/labels',
                           augment=False)

# --- DataLoaders ---
train_loader = DataLoader(train_dataset, batch_size=8,
                          shuffle=True, num_workers=2,
                          pin_memory=False, persistent_workers=True)

val_loader = DataLoader(val_dataset, batch_size=8,
                        shuffle=False, num_workers=2,
                        pin_memory=False, persistent_workers=True)

import matplotlib.pyplot as plt

# Get one batch
images, targets = next(iter(train_loader))  # images: [B,3,540,960], targets: [B,34,60]
B = images.shape[0]

# Show up to 4 samples from the batch
plt.figure(figsize=(16,8))
for i in range(min(4, B)):
    img = images[i].permute(1,2,0).numpy()             # C,H,W → H,W,C
    img = (img * np.array([0.229,0.224,0.225]) +
                 np.array([0.485,0.456,0.406]))        # unnormalize
    img = np.clip(img, 0, 1)

    lbl = targets[i].numpy()                           # 34×60 grid
    lbl_resized = cv2.resize(lbl.astype(np.float32),
                             (img.shape[1], img.shape[0]),
                             interpolation=cv2.INTER_NEAREST)

    plt.subplot(2,2,i+1)
    plt.imshow(img)
    plt.imshow(lbl_resized, alpha=0.4, cmap='Reds')    # semi-transparent overlay
    plt.title(f"Sample {i} (red = smoke)")
    plt.axis('off')

plt.tight_layout()
plt.show()

# Phase 3: DB-Net implementation (PyTorch)
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision.models import resnet50

# ----------------------------
# DB-Net model
# ----------------------------
class DBNet(nn.Module):
    """
    DB-Net as described in the paper (dual-branch, block-wise prediction).
    - Uses ResNet-50 backbone up to layer3 (so final encoder stride = 16).
    - Projects selected feature taps to `num_classes` channels with 1x1 conv.
    - Downsamples shallower taps to the deepest tap resolution, sums, and
      optionally refines with a small head.
    - Returns logits with shape [B, num_classes, H_out, W_out], where H_out,W_out
      depend on the backbone output spatial resolution (usually input/16).
    """
    def __init__(self, num_classes=2, pretrained=True, refine=True):
        super(DBNet, self).__init__()
        backbone = resnet50(weights='IMAGENET1K_V1' if pretrained else None)

        # Stem: conv1 + bn1 + relu + maxpool
        self.stem = nn.Sequential(
            backbone.conv1, backbone.bn1, backbone.relu, backbone.maxpool
        )  # After stem -> stride 4 of original input

        # ResNet stages (we take layer1..layer3)
        self.layer1 = backbone.layer1  # typically output channels = 256 (stride 4)
        self.layer2 = backbone.layer2  # output channels = 512 (stride 8)
        self.layer3 = backbone.layer3  # output channels = 1024 (stride 16)

        # Project each tapped feature to num_classes via 1x1 conv
        # (paper used 2 output channels for block-wise binary classification)
        self.proj1 = nn.Conv2d(256, num_classes, kernel_size=1)   # from layer1
        self.proj2 = nn.Conv2d(512, num_classes, kernel_size=1)   # from layer2
        self.proj3 = nn.Conv2d(1024, num_classes, kernel_size=1)  # from layer3

        # Optional small refinement head (stabilize / smooth the summed map)
        self.refine = refine
        if self.refine:
            self.head = nn.Sequential(
                nn.Conv2d(num_classes, num_classes, kernel_size=3, padding=1, bias=False),
                nn.BatchNorm2d(num_classes),
                nn.ReLU(inplace=True),
                nn.Conv2d(num_classes, num_classes, kernel_size=1)
            )
        else:
            self.head = nn.Identity()

        # initialization: small proj and head are initialized by default; you can refine if needed

    def forward(self, x):
        """
        x: [B, 3, H, W] (e.g., [B,3,540,960])
        returns: logits [B, num_classes, H_out, W_out]
        typically H_out = H/16, W_out = W/16 (but depends on exact input / padding)
        """

        # --- Encoder / Main branch ---
        s = self.stem(x)       # after conv1+maxpool -> stride 4
        f1 = self.layer1(s)    # /4 spatial, channels=256
        f2 = self.layer2(f1)   # /8 spatial, channels=512
        f3 = self.layer3(f2)   # /16 spatial, channels=1024  <-- deepest tap

        # --- Project each tap to num_classes channels ---
        p1 = self.proj1(f1)  # [B, num_classes, H1, W1]  (H1 ~ H/4)
        p2 = self.proj2(f2)  # [B, num_classes, H2, W2]  (H2 ~ H/8)
        p3 = self.proj3(f3)  # [B, num_classes, H3, W3]  (H3 ~ H/16)

        # --- Downsample p1, p2 to p3's spatial resolution and sum ---
        target_size = p3.shape[2:],  # (H3, W3)
        H3, W3 = p3.shape[2], p3.shape[3]

        # Use bilinear up/down sampling to align spatial sizes
        p1_ds = F.interpolate(p1, size=(H3, W3), mode='bilinear', align_corners=False)
        p2_ds = F.interpolate(p2, size=(H3, W3), mode='bilinear', align_corners=False)

        agg = p1_ds + p2_ds + p3  # elementwise sum --> [B, num_classes, H3, W3]

        # Optional refinement head (small conv block)
        out = self.head(agg)  # logits, not normalized

        # Important: DO NOT apply softmax here if you use CrossEntropyLoss. Return raw logits.
        return out


# ----------------------------
# Sanity-check utilities
# ----------------------------
def sanity_check_model():
    """
    Creates DBNet, feeds a dummy batch and prints shapes.
    Useful to verify output dims (B, C, H_out, W_out).
    """
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    model = DBNet(num_classes=2, pretrained=False, refine=True).to(device)
    model.eval()
    # Dummy input: batch 2, channels 3, H=540, W=960 (paper setting)
    dummy = torch.randn(2, 3, 540, 960).to(device)
    with torch.no_grad():
        logits = model(dummy)
    print("Input:", dummy.shape)
    print("Output logits:", logits.shape)
    # If using CrossEntropyLoss: pass targets shaped [B, H_out, W_out] of dtype long
    # e.g.
    B, C, Hout, Wout = logits.shape
    print("Expected target shape for CrossEntropyLoss (per sample):", (Hout, Wout))
    return model, logits

# Run sanity check
if __name__ == "__main__":
    model, logits = sanity_check_model()

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from tqdm import tqdm
import os

device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = DBNet(num_classes=2, pretrained=True).to(device)

# ---- Optional class weights (adjust after checking data imbalance) ----
class_weights = torch.tensor([1.0, 5.0]).to(device)
criterion = nn.CrossEntropyLoss(weight=class_weights)

optimizer = optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-5)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.5)

# ---------------------------
# Helper: IoU computation
# ---------------------------
def compute_iou(pred, target, num_classes=2):
    ious = []
    for cls in range(num_classes):
        pred_inds = (pred == cls)
        target_inds = (target == cls)
        intersection = (pred_inds & target_inds).sum()
        union = (pred_inds | target_inds).sum()
        if union == 0:
            ious.append(float('nan'))
        else:
            ious.append(intersection / union)
    return ious

def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss = 0
    iou_scores = []
    with torch.no_grad():
        for imgs, labels in tqdm(loader, desc="Validating", leave=False):
            imgs, labels = imgs.to(device), labels.to(device)
            logits = model(imgs)
            loss = criterion(logits, labels)
            total_loss += loss.item() * imgs.size(0)

            preds = torch.argmax(logits, dim=1).cpu().numpy()
            targets = labels.cpu().numpy()
            for p, t in zip(preds, targets):
                ious = compute_iou(p, t)
                iou_scores.append(ious)
    avg_loss = total_loss / len(loader.dataset)
    avg_ious = np.nanmean(iou_scores, axis=0)
    return avg_loss, avg_ious

# ---------------------------
# Training Loop with Checkpoint
# ---------------------------
num_epochs = 20
save_dir = "/content/drive/MyDrive/dbnet_training"
os.makedirs(save_dir, exist_ok=True)

start_epoch = 1
best_val_iou = 0.0

# ---- Resume training if checkpoint exists ----
ckpt_path = os.path.join(save_dir, "dbnet_checkpoint.pth")
if os.path.exists(ckpt_path):
    checkpoint = torch.load(ckpt_path)
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
    start_epoch = checkpoint['epoch'] + 1
    best_val_iou = checkpoint['best_val_iou']
    print(f"Resuming training from epoch {start_epoch}, best IoU {best_val_iou:.4f}")

# ---- CSV log ----
log_path = os.path.join(save_dir, "training_log.csv")
log_file = open(log_path, "a" if start_epoch > 1 else "w")
if start_epoch == 1:
    log_file.write("epoch,train_loss,val_loss,val_iou_bg,val_iou_smoke\n")

for epoch in range(start_epoch, num_epochs+1):
    model.train()
    train_loss = 0.0

    for imgs, labels in tqdm(train_loader, desc=f"Epoch {epoch}/{num_epochs}"):
        imgs, labels = imgs.to(device), labels.to(device)
        optimizer.zero_grad()
        logits = model(imgs)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()
        train_loss += loss.item() * imgs.size(0)

    train_loss /= len(train_loader.dataset)
    val_loss, val_ious = evaluate(model, val_loader, criterion, device)
    val_iou_bg, val_iou_smoke = val_ious

    # ---- Write log ----
    log_file.write(f"{epoch},{train_loss:.4f},{val_loss:.4f},{val_iou_bg:.4f},{val_iou_smoke:.4f}\n")
    log_file.flush()

    print(f"Epoch {epoch} - "
          f"Train Loss: {train_loss:.4f}, "
          f"Val Loss: {val_loss:.4f}, "
          f"IoU BG: {val_iou_bg:.4f}, IoU Smoke: {val_iou_smoke:.4f}")

    # ---- Save best model ----
    mean_val_iou = np.nanmean(val_ious)
    if mean_val_iou > best_val_iou:
        best_val_iou = mean_val_iou
        torch.save(model.state_dict(), os.path.join(save_dir, "dbnet_best.pth"))
        print(">>> Saved best model (IoU improved).")

    # ---- Always save checkpoint ----
    torch.save({
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'best_val_iou': best_val_iou
    }, ckpt_path)

    scheduler.step()

log_file.close()
print("Training finished. Best IoU:", best_val_iou)

!ls -lh /content/drive/MyDrive/dbnet_training/